// === DATOS DE EJEMPLO - EL OSO DE LA SUERTE ===
import { Rifa, PlanSaas, Organizador } from './types';

export const organizadoresEjemplo: Organizador[] = [
  {
    id: 'org-1',
    nombre: 'María González',
    email: 'maria@rifasvenezuela.com',
    telefono: '+58 412-111-2222',
    avatar: '/avatars/maria.jpg',
    verificacionKYC: true,
    plan: 'oro',
    rifasCreadas: 48,
    rifasActivas: 3,
    rifasExitosas: 45,
    calificacion: 4.9,
    descripcion: 'Organizadora verificada con más de 2 años de experiencia en rifas solidarias.',
    redesSociales: {
      instagram: '@mariagonzalez_rifas',
      whatsapp: '+584121112222',
      telegram: '@mariagonzalez',
    },
    creadoEn: new Date('2022-01-15'),
  },
  {
    id: 'org-2',
    nombre: 'Carlos Mendoza',
    email: 'carlos@osodelasuerte.com',
    telefono: '+58 424-333-4444',
    avatar: '/avatars/carlos.jpg',
    verificacionKYC: true,
    plan: 'plata',
    rifasCreadas: 22,
    rifasActivas: 2,
    rifasExitosas: 20,
    calificacion: 4.7,
    descripcion: 'Rifas benéficas para comunidades de Caracas.',
    redesSociales: {
      instagram: '@carlosmendoza_oficial',
      whatsapp: '+584243334444',
    },
    creadoEn: new Date('2023-03-10'),
  },
  {
    id: 'org-3',
    nombre: 'Luisa Pérez',
    email: 'luisa@rifaslu.com',
    telefono: '+58 416-555-6666',
    avatar: '/avatars/luisa.jpg',
    verificacionKYC: true,
    plan: 'plata',
    rifasCreadas: 15,
    rifasActivas: 1,
    rifasExitosas: 14,
    calificacion: 4.8,
    descripcion: 'Especialista en rifas de electrodomésticos y tecnología.',
    redesSociales: {
      telegram: '@luisa_rifas',
    },
    creadoEn: new Date('2023-06-20'),
  },
];

export const rifasEjemplo: Rifa[] = [
  {
    id: 'rifa-001',
    slug: 'iphone-15-pro-max-256gb',
    nombre: 'iPhone 15 Pro Max 256GB',
    descripcion:
      'Participa y gana el iPhone 15 Pro Max en color Titanio Natural con 256GB de almacenamiento. Incluye garantía oficial de Apple de 1 año, AirPods Pro de segunda generación y funda de cuero original. Sorteo verificado en vivo por Instagram.',
    premio: {
      nombre: 'iPhone 15 Pro Max 256GB',
      descripcion: 'Titanio Natural + AirPods Pro + Funda cuero',
      valorEstimado: 1200,
      moneda: 'USD',
      imagenes: [
        'https://images.unsplash.com/photo-1696446702183-8d8ca9f7c6aa?w=800',
        'https://images.unsplash.com/photo-1695048133142-1a20484429be?w=800',
      ],
      especificaciones: {
        'Almacenamiento': '256GB',
        'Color': 'Titanio Natural',
        'Pantalla': '6.7" Super Retina XDR',
        'Garantía': '1 año Apple',
        'Incluye': 'AirPods Pro + Funda cuero',
      },
    },
    organizador: organizadoresEjemplo[0],
    tickets: [],
    totalTickets: 200,
    ticketsVendidos: 156,
    precioTicket: 5,
    moneda: 'USD',
    categoria: 'electronica',
    configuracion: {
      metodosPago: ['zelle', 'pago_movil', 'binance'],
      tiempoEsperaPago: 30,
      mostrarTicketsDisponibles: true,
      mostrarBarraProgreso: true,
      permitirVendedores: true,
    },
    estado: 'activa',
    fechaInicio: new Date('2025-03-01'),
    fechaSorteo: new Date('2025-03-25'),
    destacada: true,
    vistas: 3420,
    creadoEn: new Date('2025-03-01'),
    actualizadoEn: new Date('2025-03-14'),
  },
  {
    id: 'rifa-002',
    slug: 'toyota-corolla-2024',
    nombre: 'Toyota Corolla XSE 2024',
    descripcion:
      'El sueño de tener tu propio vehículo puede hacerse realidad. Toyota Corolla XSE 2024 0km, color azul eléctrico, con todos los papeles en regla. Sorteo en vivo por YouTube con notario público presente.',
    premio: {
      nombre: 'Toyota Corolla XSE 2024',
      descripcion: 'Vehículo 0km, color Azul Eléctrico, papeles en regla',
      valorEstimado: 28000,
      moneda: 'USD',
      imagenes: [
        'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
      ],
      especificaciones: {
        'Año': '2024',
        'Color': 'Azul Eléctrico',
        'Motor': '2.0L Dynamic Force',
        'Transmisión': 'Automática CVT',
        'Kilometraje': '0 km',
        'Documentos': 'Completos y al día',
      },
    },
    organizador: organizadoresEjemplo[1],
    tickets: [],
    totalTickets: 1000,
    ticketsVendidos: 723,
    precioTicket: 30,
    moneda: 'USD',
    categoria: 'vehiculos',
    configuracion: {
      metodosPago: ['zelle', 'pago_movil', 'binance', 'efectivo'],
      tiempoEsperaPago: 60,
      mostrarTicketsDisponibles: true,
      mostrarBarraProgreso: true,
      permitirVendedores: true,
    },
    estado: 'activa',
    fechaInicio: new Date('2025-02-15'),
    fechaSorteo: new Date('2025-03-30'),
    destacada: true,
    vistas: 12800,
    creadoEn: new Date('2025-02-15'),
    actualizadoEn: new Date('2025-03-14'),
  },
  {
    id: 'rifa-003',
    slug: 'samsung-55-4k-smart-tv',
    nombre: 'Samsung Neo QLED 55" 4K',
    descripcion:
      'Transforma tu sala con el Samsung Neo QLED 55" 4K. Tecnología Quantum Matrix, procesador Neural Quantum 4K, sonido Dolby Atmos. Incluye instalación y envío a cualquier ciudad de Venezuela.',
    premio: {
      nombre: 'Samsung Neo QLED 55" 4K',
      descripcion: 'Smart TV 4K con instalación incluida a domicilio',
      valorEstimado: 1800,
      moneda: 'USD',
      imagenes: [
        'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=800',
      ],
      especificaciones: {
        'Tamaño': '55 pulgadas',
        'Resolución': '4K UHD',
        'Tecnología': 'Neo QLED',
        'Sistema': 'Tizen Smart TV',
        'Sonido': 'Dolby Atmos',
        'Incluye': 'Instalación + Envío',
      },
    },
    organizador: organizadoresEjemplo[2],
    tickets: [],
    totalTickets: 300,
    ticketsVendidos: 187,
    precioTicket: 7,
    moneda: 'USD',
    categoria: 'electronica',
    configuracion: {
      metodosPago: ['zelle', 'pago_movil', 'binance'],
      tiempoEsperaPago: 30,
      mostrarTicketsDisponibles: true,
      mostrarBarraProgreso: true,
      permitirVendedores: false,
    },
    estado: 'activa',
    fechaInicio: new Date('2025-03-05'),
    fechaSorteo: new Date('2025-03-28'),
    destacada: true,
    vistas: 5670,
    creadoEn: new Date('2025-03-05'),
    actualizadoEn: new Date('2025-03-14'),
  },
  {
    id: 'rifa-004',
    slug: 'ps5-bundle-2-controles',
    nombre: 'PlayStation 5 Bundle',
    descripcion:
      'La consola más deseada del momento. PlayStation 5 con 2 controles DualSense, God of War Ragnarök y Spider-Man 2. Sorteo el 1 de abril en vivo por Instagram con ONG verificada como testigo.',
    premio: {
      nombre: 'PlayStation 5 Bundle',
      descripcion: 'PS5 + 2 controles + 2 juegos',
      valorEstimado: 900,
      moneda: 'USD',
      imagenes: [
        'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800',
      ],
      especificaciones: {
        'Incluye': 'Consola PS5 + 2 DualSense',
        'Juegos': 'God of War Ragnarök + Spider-Man 2',
        'Almacenamiento': '825GB SSD',
        'Resolución': 'Hasta 8K',
        'Condición': 'Nuevo en caja',
      },
    },
    organizador: organizadoresEjemplo[0],
    tickets: [],
    totalTickets: 150,
    ticketsVendidos: 98,
    precioTicket: 8,
    moneda: 'USD',
    categoria: 'electronica',
    configuracion: {
      metodosPago: ['zelle', 'binance', 'pago_movil'],
      tiempoEsperaPago: 30,
      mostrarTicketsDisponibles: true,
      mostrarBarraProgreso: true,
      permitirVendedores: true,
    },
    estado: 'activa',
    fechaInicio: new Date('2025-03-10'),
    fechaSorteo: new Date('2025-04-01'),
    destacada: false,
    vistas: 4230,
    creadoEn: new Date('2025-03-10'),
    actualizadoEn: new Date('2025-03-14'),
  },
  {
    id: 'rifa-005',
    slug: 'efectivo-500-dolares',
    nombre: '$500 en Efectivo',
    descripcion:
      'Simple y directo: participa y gana $500 en efectivo entregados en mano. Sin complicaciones, sin demoras. El ganador recibe su dinero en 24 horas después del sorteo. Verificado y transparente.',
    premio: {
      nombre: '$500 Dólares en Efectivo',
      descripcion: 'Entrega inmediata en 24 horas al ganador',
      valorEstimado: 500,
      moneda: 'USD',
      imagenes: [
        'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
      ],
      especificaciones: {
        'Monto': '$500 USD',
        'Entrega': 'En mano o transferencia',
        'Plazo': '24 horas post-sorteo',
      },
    },
    organizador: organizadoresEjemplo[1],
    tickets: [],
    totalTickets: 100,
    ticketsVendidos: 67,
    precioTicket: 6,
    moneda: 'USD',
    categoria: 'dinero',
    configuracion: {
      metodosPago: ['zelle', 'pago_movil', 'binance'],
      tiempoEsperaPago: 20,
      mostrarTicketsDisponibles: true,
      mostrarBarraProgreso: true,
      permitirVendedores: false,
    },
    estado: 'activa',
    fechaInicio: new Date('2025-03-12'),
    fechaSorteo: new Date('2025-03-22'),
    destacada: false,
    vistas: 2890,
    creadoEn: new Date('2025-03-12'),
    actualizadoEn: new Date('2025-03-14'),
  },
  {
    id: 'rifa-006',
    slug: 'macbook-air-m3-2024',
    nombre: 'MacBook Air M3 2024',
    descripcion:
      'El MacBook Air más potente jamás creado. Chip M3, 16GB RAM, 512GB SSD en color Medianoche. Perfecto para trabajo, diseño y estudio. Incluye Magic Mouse, Magic Keyboard y adaptador USB-C.',
    premio: {
      nombre: 'MacBook Air M3',
      descripcion: '16GB RAM + 512GB SSD + accesorios',
      valorEstimado: 1500,
      moneda: 'USD',
      imagenes: [
        'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
      ],
      especificaciones: {
        'Chip': 'Apple M3',
        'RAM': '16GB',
        'Almacenamiento': '512GB SSD',
        'Color': 'Medianoche',
        'Pantalla': '13.6" Liquid Retina',
        'Incluye': 'Magic Mouse + Magic Keyboard',
      },
    },
    organizador: organizadoresEjemplo[2],
    tickets: [],
    totalTickets: 250,
    ticketsVendidos: 89,
    precioTicket: 8,
    moneda: 'USD',
    categoria: 'electronica',
    configuracion: {
      metodosPago: ['zelle', 'binance'],
      tiempoEsperaPago: 30,
      mostrarTicketsDisponibles: true,
      mostrarBarraProgreso: true,
      permitirVendedores: false,
    },
    estado: 'activa',
    fechaInicio: new Date('2025-03-08'),
    fechaSorteo: new Date('2025-04-08'),
    destacada: false,
    vistas: 3150,
    creadoEn: new Date('2025-03-08'),
    actualizadoEn: new Date('2025-03-14'),
  },
];

export const planesEjemplo: PlanSaas[] = [
  {
    id: 'bronce',
    nombre: 'Oso Bronce',
    icono: '🥉',
    precio: 19,
    moneda: 'USD',
    intervalo: 'mes',
    rifasSimultaneas: 1,
    ticketsPorRifa: 100,
    caracteristicas: [
      '1 rifa activa simultánea',
      'Hasta 100 tickets por rifa',
      'Subdominio gratis (rifa.tunombre.com)',
      'Pagos: Zelle + Pago Móvil',
      'Sistema de vouchers (WhatsApp)',
      'Panel de estadísticas básico',
      'Soporte por email (24-48h)',
      'SSL incluido',
      'Sorteo con algoritmo verificable',
    ],
    destacado: false,
    color: '#CD7F32',
  },
  {
    id: 'plata',
    nombre: 'Oso Plata',
    icono: '🥈',
    precio: 49,
    moneda: 'USD',
    intervalo: 'mes',
    rifasSimultaneas: 3,
    ticketsPorRifa: 500,
    caracteristicas: [
      '3 rifas activas simultáneas',
      'Hasta 500 tickets por rifa',
      'Dominio personalizado incluido',
      'Todos los métodos de pago venezolanos',
      'Sistema de vendedores (hasta 5)',
      'Analytics básico + Pixel Facebook',
      'Soporte WhatsApp (respuesta en 12h)',
      'Multi-canal de vouchers (WhatsApp + Email)',
      'Sistema de descuentos y promociones',
      'Barra de progreso personalizable',
    ],
    destacado: true,
    color: '#C0C0C0',
  },
  {
    id: 'oro',
    nombre: 'Oso Oro',
    icono: '🥇',
    precio: 99,
    moneda: 'USD',
    intervalo: 'mes',
    rifasSimultaneas: 'ilimitado',
    ticketsPorRifa: 'ilimitado',
    caracteristicas: [
      'Rifas y tickets ilimitados',
      'Dominio personalizado + SSL premium',
      'Todos los métodos de pago + Cripto',
      'Vendedores ilimitados con comisiones',
      'Analytics avanzado + A/B Testing',
      'OCR automático para vouchers (60 seg)',
      'Backup triple de comprobantes (5 años)',
      'Streaming integrado (YouTube + Facebook)',
      'Soporte prioritario 24/7',
      'Verificación KYC para premios >$100',
      'App móvil personalizada incluida',
      'API pública para integraciones',
    ],
    destacado: false,
    color: '#FFD700',
  },
];

export const estadisticasPlataforma = {
  rifasActivas: 347,
  organizadoresVerificados: 124,
  ticketsVendidos: 48230,
  premiosEntregados: 289,
  montoTotalPremios: 2850000,
};

export const categoriasRifa = [
  { id: 'electronica', nombre: 'Electrónica', emoji: '📱', color: 'bg-blue-100 text-blue-700' },
  { id: 'vehiculos', nombre: 'Vehículos', emoji: '🚗', color: 'bg-red-100 text-red-700' },
  { id: 'hogar', nombre: 'Hogar', emoji: '🏠', color: 'bg-yellow-100 text-yellow-700' },
  { id: 'dinero', nombre: 'Efectivo', emoji: '💵', color: 'bg-green-100 text-green-700' },
  { id: 'viajes', nombre: 'Viajes', emoji: '✈️', color: 'bg-purple-100 text-purple-700' },
  { id: 'joyas', nombre: 'Joyas', emoji: '💎', color: 'bg-pink-100 text-pink-700' },
  { id: 'otros', nombre: 'Otros', emoji: '🎁', color: 'bg-gray-100 text-gray-700' },
];

export const metodosPagoInfo = {
  zelle: { nombre: 'Zelle', emoji: '🏦', color: '#6933FF' },
  pago_movil: { nombre: 'Pago Móvil', emoji: '📲', color: '#00B8D9' },
  binance: { nombre: 'Binance', emoji: '🟡', color: '#F0B90B' },
  efectivo: { nombre: 'Efectivo', emoji: '💵', color: '#228B22' },
  stripe: { nombre: 'Tarjeta', emoji: '💳', color: '#635BFF' },
  paypal: { nombre: 'PayPal', emoji: '🔵', color: '#003087' },
  usdt: { nombre: 'USDT', emoji: '🪙', color: '#26A17B' },
};
